name: java-jboss-eap-xp-bootable-jar
displayName: JBoss EAP XP 2.0 Bootable Jar
description: Java stack with EAP XP 2.0 in bootable Jar mode, OpenJDK 11 and Maven 3.5
tags:  ["RHEL8", "Java", "OpenJDK", "Maven", "EAP", "Microprofile", "EAP XP Bootable"]
projectType: "JBoss EAP XP"
language: "java"
