---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: PROJECT_NAME
  labels:
    app.kubernetes.io/instance: PROJECT_NAME
    app.kubernetes.io/name: PROJECT_NAME
    app.kubernetes.io/part-of: PROJECT_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PROJECT_NAME
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: PROJECT_NAME
    spec:
      containers:
        - name: PROJECT_NAME
          image: CONTAINER_IMAGE
          ports:
            - name: http
              containerPort: PORT
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: PROJECT_NAME
spec:
  ports:
    - protocol: TCP
      port: PORT
      targetPort: PORT
  selector:
    app: PROJECT_NAME
  type: ClusterIP
  sessionAffinity: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: PROJECT_NAME
  labels:
    app.kubernetes.io/instance: PROJECT_NAME
    app.kubernetes.io/name: PROJECT_NAME
    app.kubernetes.io/part-of: PROJECT_NAME
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: PROJECT_NAME
    weight: 100
  port:
    targetPort: PORT
  wildcardPolicy: None